### ISSUE TITLE
Pretrained weights ?

### ISSUE THREAD

**Issue by rishikksh20** [PolyAI-LDN/pheme#1]
Hi
Are you planning to share pretrained weights or built some demo where I test this model.
Also have test this model with Vocos vocoder rather than speechtokenizer generated audio codec?

**Comment by rishikksh20** [comment]
Ok get the pretrained model huggingface links : https://huggingface.co/PolyAI/pheme

**Comment by pawel-polyai** [comment]
Hey,

please see the readme. We shared two models along with the instructions on loading them.
