### ISSUE TITLE
About Producing Manifest File

### ISSUE THREAD

**Issue by nonmetal** [PolyAI-LDN/pheme#10]
Hello, thank you for providing a wonderful repository.
I would like to ask a question about how to obtain information in order to produce manifest file.

```
{
    "LJ001-0051.wav": {
      "text": "and paying great attention to the press work or actual process of printing,",
      "raw-text": "and paying great attention to the press work or actual process of printing,",
      "duration": 4.860090702947846,
      "phoneme": "æ|n|d|_|p|eɪ|ɪ|ŋ|_|ɡ|ɹ|eɪ|t|_|ɐ|t|ɛ|n|ʃ|ə|n|_|t|ə|_|ð|ə|_|\"|p|ɹ|ɛ|s|_|w|ɜː|k|\"|_|ɔː|ɹ|_|æ|k|tʃ|uː|əl|_|p|ɹ|ɑː|s|ɛ|s|_|ʌ|v|_|p|ɹ|ɪ|n|t|ɪ|ŋ|,"
    },
    "LJ001-0120.wav": {
    ...
    },
    ...
}
```

In the format of manifest file above, although there is a transcribed data of the audio file, getting `duration` and `phoneme` from the following data should need extra pre-processing, and the method nor code to create these information doesn't seem to presented in the repository. 

Thus, I would like to ask: what libraries did you use for producing those information? 
Also, if you used codes to produce the manifest file in your experiments, I would like to carefully ask if you could provide the code.

Thank you.

**Comment by taras-sereda** [comment]
Hi @nonmetal thank you for the interest in our work!

We added necessary scripts in the repository to generate manifests for both model training and evaluation.
Please consult the updated [readme section](https://github.com/PolyAI-LDN/pheme?tab=readme-ov-file#data-preparation)
